### PR TITLE
Fix bad escape

### LINKED ISSUE #14: Error: bad escape \e
The two occurrences of the line below in _sphinxcontrib_robotdoc.py_ cause an error:
`parsed = regex.sub('\end{Verbatim}\n', parsed)`
Raises `re.error: bad escape \e at position 0 (line 1, column 1)`

The error no longer occurs after adding two `\` characters:
`parsed = regex.sub('\\\end{Verbatim}\n', parsed)`

I'd open a PR, but it seems I'm not allowed to push my branch.

### PR DESCRIPTION
**Pull request by JasperCraeghs**
Resolves https://github.com/datakurre/sphinxcontrib-robotdoc/issues/14

### CODE REVIEW

**Review by datakurre — APPROVED** [review]

**Comment by datakurre** [comment]
Thanks. I blindly released 0.11.0 and would be grateful if you could test and confirm it works as expected.

**Comment by JasperCraeghs** [comment]
I successfully built the example documentation of [mlx.robot2rst](https://github.com/melexis/robot2rst) with the 0.11.0 release. It works as expected.

**Comment by datakurre** [comment]
@JasperCraeghs Thanks for trying this out.

As an afterthought, it would have been enough, probably, to make those strings raw-strings as in `r'\end{Verbatim}\n'`.

**Comment by JasperCraeghs** [comment]
I just tried you suggestion, but your raw string doesn't contain enough escape characters and results in the same `re.error: bad escape \e at position 0`.

Solution: `r'\\end{Verbatim}\n'`

**Comment by datakurre** [comment]
Thanks that makes sense.

**Pull request merged**
